name: firelink_audio
description: "FireLink Audio — Open-source music streaming client built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Audio — media_kit (MPV)
  media_kit: ^1.1.11
  media_kit_libs_windows_audio: ^1.0.9
  media_kit_libs_android_audio: ^1.3.8

  # YouTube (sem servidor, sem API key)
  youtube_explode_dart: ^3.0.5

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency injection
  get_it: ^9.2.0

  # Reactive streams
  rxdart: ^0.28.0

  # HTTP client
  http: ^1.4.0

  # Image caching
  cached_network_image: ^3.4.1

  # Fonts
  google_fonts: ^8.0.2

  # Local storage
  shared_preferences: ^2.3.4
  path_provider: ^2.1.2

  # External links
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
